# Generated by Django 4.2.14 on 2025-09-03 15:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve ter 11 números', regex='^\\d{11}$')])),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('perfil', models.CharField(choices=[('ADMIN', 'Administrador'), ('TECNICO_SST', 'Técnico SST'), ('ALMOXARIFE', 'Almoxarife'), ('COLABORADOR', 'Colaborador')], default='COLABORADOR', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
