# Generated by Django 4.2.14 on 2025-09-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('ca_numero', models.CharField(blank=True, max_length=30, null=True)),
                ('ca_validade', models.DateField(blank=True, null=True)),
                ('tamanho', models.CharField(blank=True, max_length=20, null=True)),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('FORNECIDO', 'Fornecido'), ('EMPRESTADO', 'Emprestado'), ('DEVOLVIDO', 'Devolvido'), ('DANIFICADO', 'Danificado'), ('PERDIDO', 'Perdido')], default='FORNECIDO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
